name: Optimize map and deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master

      - name: Bash
        run: |
          git config --global user.email "map-optimizer@github.action"
          git config --global user.name "Map Optimizer"
          git checkout master
          git commit -am "Adding files"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          BASE_BRANCH: master
